### ISSUE TITLE
Device id follow up request

### ISSUE THREAD

**Issue by BarryAllenJr** [ch4kn/tiktok-device-register#1]
Hey, i'm getting `new_user 1`, getting the device id but it's still not working. I've read on some Chinese forum that there is an additional log request after that. Do you know anything about it?

**Comment by ch4kn** [comment]
Yes i know.

**Comment by BarryAllenJr** [comment]
Can you tell which endpoint is used for approve request?

**Comment by ch4kn** [comment]
I give as api
